### ISSUE TITLE
`TypeError: Class extends value undefined is not a constructor or null` when using `esbuild`

### ISSUE THREAD

**Issue by tresabhi** [yisibl/resvg-js#233]
Minimum reproducible code:
```tsx
new Resvg('');
```

Build command:
```bash
esbuild index.ts --outfile=index.js --bundle --platform=node --loader:.node=file
```

Full error:
```log
/workspace/sklld-bot/dist/index.cjs:230
    module2.exports.Resvg = class Resvg extends _Resvg {
                                                ^

TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@resvg/resvg-js/index.js (/workspace/sklld-bot/dist/index.cjs:230:49)
    at __require (/workspace/sklld-bot/dist/index.cjs:9:50)
    at Object.<anonymous> (/workspace/sklld-bot/dist/index.cjs:239:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by tresabhi** [comment]
Using a copy loader for `.node` files fixes this:

```bash
esbuild <input> --outfile=<output> --loader:.node=copy
```
