### ISSUE TITLE
SvelteKit problem

### ISSUE THREAD

**Issue by leokolt** [yisibl/resvg-js#264]
Hi. I have a project on Sveltekit, it uses adapter-node. I use resvg in order to create images for social networks on the fly, something like `og/vercel' does. 

I used the instructions from this article https://geoffrich.net/posts/svelte-social-image/.  Here is the code where I use resvg:

```
import {html as toReactNode} from 'satori-html';
import Card from '$lib/components/globals/Card.svelte';

import satori from 'satori';
import { Resvg } from '@resvg/resvg-js';
import FontRegular from '$lib/assets/fonts/WorkSans-Medium.ttf'


const height = 630;
const width = 1200;

/** @type {import('./$types').RequestHandler} */
export const GET = async ({url}) => {
    const title = url.searchParams.get('title') ?? undefined;
    const description = url.searchParams.get('description') ?? undefined;
    const result = Card.render({title, description});
    const html = toReactNode(`${result.html}`);

  const svg = await satori(html, {
    fonts: [
      {
        name: 'Work Sans',
        data: Buffer.from(FontRegular),
        style: 'normal',
        weight: 500
      },
    ],
    height,
    width
  });

  const resvg = new Resvg(svg, {
    fitTo: {
      mode: 'width',
      value: width
    }
  });

  const image = resvg.render();

  return new Response(image.asPng(), {
    headers: {
      'content-type': 'image/png'
    }
  });
};

```
The problem is that when I do work with a project in development mode everything works. I know for sure that the problem is in resvg because if you delete the line `import{Resvg } from '@resvg/resvg-js';` then the build ends successfully. But when I do build, I get an error:

```
> Using @sveltejs/adapter-node
error during build:
RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///C:/svelte/koltandev/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///C:/svelte/koltandev/node_modules/rollup/dist/es/shared/node-entry.js:13740:16)
    at Module.tryParse (file:///C:/svelte/koltandev/node_modules/rollup/dist/es/shared/node-entry.js:14471:25)
    at Module.setSource (file:///C:/svelte/koltandev/node_modules/rollup/dist/es/shared/node-entry.js:14072:39)
    at ModuleLoader.addModuleSource (file:///C:/svelte/koltandev/node_modules/rollup/dist/es/shared/node-entry.js:24644:20)    
```

I found a similar problem in a person https://stackoverflow.com/questions/75782642/importing-library-with-native-module-causes-vite-build-to-fail and did everything that is indicated there (deleted and added the package, added options to `vite.config.js`), but nothing helped me. This is how my file looks like `vite.config.js`:

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { imagetools } from '@zerodevx/svelte-img/vite'
import fs from 'fs'

export default defineConfig({
	plugins: [
        sveltekit(),
        imagetools({
            runDefaultDirectives: new URLSearchParams('w=480w;1024;1920&format=webp;jpg')
        }),
        rawFonts(['.ttf'])
    ],
    assetsInclude: ['**/*.md'],
    build: {
        rollupOptions: {
          external: ["@resvg/resvg-js"],
          output: {
            globals: { "@resvg/resvg-js": "Resvg" }
          }
        },
    }
});

function rawFonts(ext) {
	return {
		name: 'vite-plugin-raw-fonts',
		transform(code, id) {
			if (ext.some((e) => id.endsWith(e))) {
				const buffer = fs.readFileSync(id);
				return { code: `export default ${JSON.stringify(buffer)}`, map: null };
			}
		}
	};
}

```

Is there any way to solve this problem?

**Comment by leokolt** [comment]
I removed the package in my file.json @resvg-js from devDepependencies to dependencies and everything worked
