### ISSUE TITLE
@resvg/resvg-js-linux-x64-musl: Arch linux: TypeError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by btakita** [yisibl/resvg-js#267]
When requiring @resvg/resvg-js-linux-x64-musl on arch, I get the following error:

```
TypeError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
      at internalRequire (:1:20)
      at /home/brian/project/tmp/test.js:1:6
      at globalThis (/home/brian/project/tmp/test.js:2:17)
```

The loader file is:

```
const foo = require('@resvg/resvg-js-linux-x64-musl')
console.debug(foo)
```

**Comment by btakita** [comment]
It's test code to isolate the issue.

**Comment by yisibl** [comment]
https://stackoverflow.com/questions/53856733/libc-musl-x86-64-so-1-cannot-open-shared-object-file
